# Generated by Django 4.1.5 on 2025-09-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartxerox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='smartxerox',
        ),
    ]
