# Generated by Django 5.2.6 on 2025-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartxerox', '0002_delete_smartxerox'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
