# Generated by Django 5.2.6 on 2025-11-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartxerox', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_collections',
        ),
    ]
