# Generated by Django 6.0 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartxerox', '0004_delete_customer_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('max_upload_size', models.IntegerField(default=20)),
                ('allowed_formats', models.JSONField(default=list)),
                ('auto_delete_days', models.IntegerField(default=7)),
                ('working_start_time', models.TimeField(default='09:00')),
                ('working_end_time', models.TimeField(default='21:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
