# Generated by Django 6.0 on 2026-02-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartxerox', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
                ('copies', models.IntegerField(default=1)),
                ('print_type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('printing', 'Printing'), ('paused', 'Paused'), ('done', 'Done'), ('failed', 'Failed')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
