# Generated by Django 6.0 on 2026-02-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartxerox', '0006_printorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
